export const metadata = { title: "Privacy Policy — MentaAgent" };

const EFFECTIVE_DATE = "2026-06-08";

export default function PrivacyPage() {
  return (
    <>
      <h1 className="text-3xl font-semibold">Privacy Policy</h1>
      <p className="text-xs text-neutral-500">Effective {EFFECTIVE_DATE}</p>

      <Section title="1. What this policy covers">
        <p>
          This policy explains what data MentaAgent collects when you use
          the Service at mentapath.com, how we use it, who we share it
          with, and the choices you have. By using the Service you consent
          to the practices described here.
        </p>
      </Section>

      <Section title="2. Data we collect">
        <p>
          <strong>Account data.</strong> Email, name, hashed password,
          profile photo (from OAuth provider, if used), workspace name,
          role (admin / member), workspace and account creation dates.
        </p>
        <p>
          <strong>Content data.</strong> Files you upload (spreadsheets,
          PDFs, documents, emails), reports and analyses generated by
          the Service from your uploads, queries you ask, alerts created
          for your workspace, and an activity log of those events.
        </p>
        <p>
          <strong>Billing data.</strong> A Paddle customer ID, subscription
          status, plan, and current billing period. We do not store full
          payment card numbers; Paddle stores those.
        </p>
        <p>
          <strong>Technical data.</strong> IP address (used for rate
          limiting and abuse detection), user agent, request paths, HTTP
          status codes, and error reports. We track failed login attempts
          and authentication events in an audit log.
        </p>
        <p>
          <strong>AI usage data.</strong> Per-workspace counts of language
          model calls, input/output tokens, and computed cost. This drives
          the usage gauge on your billing page.
        </p>
        <p>
          We do not collect or process information about your health,
          financial accounts, political views, religious beliefs, sexual
          orientation, or biometrics. Do not upload such categories of
          content.
        </p>
      </Section>

      <Section title="3. Cookies and tracking">
        <p>
          We use a small number of strictly-necessary cookies:
        </p>
        <ul className="list-disc space-y-1 pl-6">
          <li>
            <strong>Session cookies</strong> (
            <code className="font-mono text-xs">__Secure-authjs.*</code>,{" "}
            <code className="font-mono text-xs">__Host-authjs.*</code>) —
            HttpOnly, Secure, SameSite=Lax. Keep you logged in. Set by
            NextAuth.
          </li>
          <li>
            <strong>CSRF token</strong> — protects state-changing requests.
          </li>
        </ul>
        <p>
          We do not use third-party advertising cookies, analytics
          trackers, or fingerprinting.
        </p>
      </Section>

      <Section title="4. Why we process your data">
        <ul className="list-disc space-y-1 pl-6">
          <li>
            <strong>To provide the Service</strong> — parse your uploads,
            analyze your business, answer your queries. Legal basis: performance
            of the contract you accept by agreeing to our Terms.
          </li>
          <li>
            <strong>To process payments</strong> — bill you for paid
            subscriptions. Legal basis: contractual necessity.
          </li>
          <li>
            <strong>To secure the Service</strong> — rate-limit abuse,
            detect intrusion, audit-log security-relevant events. Legal
            basis: our legitimate interest in protecting the Service and
            other customers.
          </li>
          <li>
            <strong>To communicate</strong> — send transactional emails
            (password resets, invoice failures, security alerts). Legal
            basis: contract / legitimate interest.
          </li>
          <li>
            <strong>To comply with law</strong> — respond to lawful
            requests and meet tax / accounting obligations.
          </li>
        </ul>
        <p>
          <strong>We do not</strong> use Your Content to train language
          models, sell your data, or share it with advertisers.
        </p>
      </Section>

      <Section title="5. Third-party processors">
        <p>
          To run the Service we share specific data with vetted vendors.
          Each processes data on our instructions and under their own
          privacy terms:
        </p>
        <ul className="list-disc space-y-1 pl-6">
          <li>
            <strong>DeepInfra</strong> (U.S.): your uploaded content
            and queries are sent here for AI inference. DeepInfra
            serves the DeepSeek model from U.S.-based infrastructure and,
            per their terms, does not use API inputs or outputs to train
            models, subject to DeepInfra&apos;s own privacy practices.
          </li>
          <li>
            <strong>Paddle</strong> (Paddle.com Market Limited, UK): payment
            card data, billing address, subscription state. Paddle acts as
            our merchant of record and is responsible for collecting and
            remitting sales tax / VAT.
          </li>
          <li>
            <strong>Resend</strong> (U.S.): destination email + the
            transactional email body (sign-in links, password resets,
            invoice failures).
          </li>
          <li>
            <strong>Railway</strong> (U.S.): hosts our application, the
            Postgres database that stores account + content metadata, and
            the file volume that stores your uploaded files.
          </li>
          <li>
            <strong>Cloudflare</strong> (global): DNS, captcha (Turnstile),
            edge proxying. Sees IP addresses and request metadata.
          </li>
          <li>
            <strong>Sentry</strong> (U.S.): error stack traces and request
            metadata when something crashes. Configured to scrub
            cookies and Authorization headers.
          </li>
          <li>
            <strong>Google</strong>: only if you sign in via Google
            OAuth — we receive your name, email, and profile photo from
            Google.
          </li>
        </ul>
      </Section>

      <Section title="6. International transfers">
        <p>
          All of the processors above are based in the United States
          (Cloudflare operates globally for edge proxying). If you are
          located outside the U.S., your data will be transferred to and
          processed there. Where applicable we rely on the EU Standard
          Contractual Clauses (or equivalent local mechanism) for
          international transfers.
        </p>
      </Section>

      <Section title="7. How long we keep data">
        <ul className="list-disc space-y-1 pl-6">
          <li>
            <strong>Your Content</strong> — for as long as your account is
            active. On account or workspace deletion, hard-deleted within
            30 days from primary storage and an additional 30 days from
            backups.
          </li>
          <li>
            <strong>Audit log</strong> — 12 months, then deleted.
          </li>
          <li>
            <strong>Billing records</strong> — at least 7 years, as
            required by tax law.
          </li>
          <li>
            <strong>Sentry error reports</strong> — 90 days, per Sentry
            defaults.
          </li>
        </ul>
      </Section>

      <Section title="8. Your rights">
        <p>Depending on where you live, you may have the right to:</p>
        <ul className="list-disc space-y-1 pl-6">
          <li>Access the personal data we hold about you.</li>
          <li>
            Correct inaccuracies (most fields are editable from{" "}
            <a href="/settings" className="underline">Settings</a>).
          </li>
          <li>
            Delete your account and Your Content (Settings → Delete
            account).
          </li>
          <li>Export your data in a portable format — email us.</li>
          <li>Withdraw consent for processing where consent is the basis.</li>
          <li>
            Lodge a complaint with your local data protection authority.
          </li>
        </ul>
        <p>
          To exercise these rights, email{" "}
          <a href="mailto:privacy@mentapath.com" className="underline">
            privacy@mentapath.com
          </a>
          . We respond within 30 days.
        </p>
      </Section>

      <Section title="9. Security">
        <p>
          We use industry-standard measures: TLS 1.3 in transit, bcrypt
          for password hashes, isolated per-workspace storage, parameterized
          SQL queries, captcha + rate limiting on authentication routes,
          and strict Content Security Policy headers. Despite these
          measures, no system is perfectly secure. If we discover a breach
          affecting your data, we will notify you and, where required, the
          appropriate regulator within 72 hours.
        </p>
      </Section>

      <Section title="10. Children">
        <p>
          The Service is intended for business use and is not directed to
          children under 18. We do not knowingly collect data from
          children. If you believe a child has provided data to us,
          contact us and we will delete it.
        </p>
      </Section>

      <Section title="11. Changes to this policy">
        <p>
          We may update this policy as the Service evolves. Material
          changes will be announced via email and at least 14 days before
          they take effect.
        </p>
      </Section>

      <Section title="12. Contact">
        <p>
          Privacy questions or requests:{" "}
          <a href="mailto:privacy@mentapath.com" className="underline">
            privacy@mentapath.com
          </a>
          . Security disclosures:{" "}
          <a href="mailto:security@mentapath.com" className="underline">
            security@mentapath.com
          </a>
          .
        </p>
      </Section>
    </>
  );
}

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="space-y-2">
      <h2 className="mt-6 text-xl font-semibold">{title}</h2>
      {children}
    </section>
  );
}
